services:
  textomos:
    image: textomos
    container_name: textomos
    build: .
    volumes:
      - type: bind
        source: ./textomos
        target: /textomos
        read_only: false
      - type: bind
        source: /tmp/.X11-unix
        target: /tmp/.X11-unix
        read_only: true
      - type: bind
        source: ${XAUTHORITY}
        target: /root/.Xauthority
        read_only: true
    environment:
      - DISPLAY=${DISPLAY}
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    ipc: host
    ports:
      - 12345:6006