version: '3'

services:
  tex-ray:
    image: tex-ray
    container_name: tex-ray
    build: .
    volumes:
      - type: bind
        source: ./stl-files
        target: /stl-files
        read_only: false
      - type: bind
        source: /tmp/.X11-unix
        target: /tmp/.X11-unix
        read_only: true
      - type: bind
        source: ${XAUTHORITY}
        target: /root/.Xauthority
        read_only: true
    environment:
      - DISPLAY=${DISPLAY}
      - NVIDIA_DRIVER_CAPABILITIES=all 
      - __NV_PRIME_RENDER_OFFLOAD=1      # These two are needed for OpenGL
      - __GLX_VENDOR_LIBRARY_NAME=nvidia # to utilize the discrete laptop GPU.
    
    # This is for CUDA
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [compute, utility, graphics, display]
              device_ids: ['0']

